# Generated by Copilot on 2025-12-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_daysummary_remove_task_is_done_task_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeLog",
        ),
        migrations.RemoveField(
            model_name="daysummary",
            name="total_logged_minutes",
        ),
    ]
