# Generated by Django 5.2.8 on 2025-12-04 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_timelog_and_adjust_daysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='focus_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_tasks', to='core.focussession'),
        ),
        migrations.AddField(
            model_name='task',
            name='focused',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.task')),
            ],
        ),
    ]
