# Generated by Django 5.2.8 on 2025-12-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_background_color_task_color_task_focus_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='focused',
        ),
    ]
