# Generated by Django 5.2.8 on 2025-12-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_task_focused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='focus_session',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AlterField(
            model_name='task',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
