# Generated by Django 5.2.8 on 2025-12-04 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_task_focus_session_remove_task_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
