# Generated by Django 5.2.8 on 2025-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_task_background_color_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
