# Generated by Django 5.2.8 on 2025-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_block_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
