# Generated by Django 5.2.8 on 2025-12-04 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_block_desc_alter_block_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='daysummary',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
    ]
