# Generated by Django 5.2.8 on 2025-12-05 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_block_desc_alter_block_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='theme_color',
            field=models.CharField(default='#10b981', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
