# Generated by Django 5.2.8 on 2025-12-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_require_user_ownership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='daysummary',
            name='unique_daysummary_user_date',
        ),
    ]
