# Generated by Django 5.2.8 on 2025-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_note_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
