# Generated by Django 5.2.8 on 2025-12-23

import django.utils.timezone
from django.db import migrations, models


def backfill_block_end_date(apps, schema_editor):
    Block = apps.get_model("core", "Block")
    # Backfill any historical NULL end_date values to keep migration safe.
    # Use start_date (most sensible) falling back to now.
    Block.objects.filter(end_date__isnull=True).update(end_date=models.F("start_date"))
    Block.objects.filter(end_date__isnull=True).update(end_date=django.utils.timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_block_done"),
    ]

    operations = [
        migrations.RunPython(backfill_block_end_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="block",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
