# Generated by Django 5.2.8 on 2025-12-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
